### ISSUE TITLE
Tooltip Rendering Outside Frame

### ISSUE THREAD

**Issue by mangowebdesign** [Linkurious/linkurious.js#110]
I know the tooltip can be changed from top, bottom, left, right. However, how can the tooltip position be changed according to the position of the node that was hovered upon ('overNode')?
![screen shot 2015-05-21 at 8 27 22 am](https://cloud.githubusercontent.com/assets/6474505/7748510/3e700a82-ff93-11e4-803a-5856a32d09f4.png)

**Comment by sheymann** [comment]
Hello,

Set the setting `autoadjust` to `true` to adjust the tooltip position to be fully included in the canvas. However this feature is experimental and it doesn't work on Firefox.

See config options in https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.plugins.tooltips

**Comment by mangowebdesign** [comment]
This does not seem to work often. I have included my JavaScript and CSS. The CSS was pulled from the tooltip example. I'm not sure if it has anything to do with that. I have included images about how some will work, yet some may be outside the window, even though they are neighbors a few pixels away. 
![screen shot 2015-05-22 at 5 32 59 pm](https://cloud.githubusercontent.com/assets/6474505/7780120/1590a380-00a9-11e5-835b-b32a00da4ca0.png)
![screen shot 2015-05-22 at 5 33 11 pm](https://cloud.githubusercontent.com/assets/6474505/7780121/198fc3d0-00a9-11e5-8b5c-05948bddd554.png)



```javascript
$(function(){
	"use strict";

/**
 * This is an example on how to use node tooltips based on a random graph
 * and with multiple sigma instances.
 */
var i,
    s,
    N = 2500,
    E = 1500,
    g = {
      nodes: [],
      edges: []
    };

// Generate a random graph:
for (i = 0; i < N; i++)
  g.nodes.push({
    id: 'n' + i,
    label: 'Node ' + i,
    x: Math.random(),
    y: Math.random(),
    size: Math.random(),
    color: '#666',
    data: {
      name: 'Jean',
      gender: 'Male',
      age: 28,
      city: 'Paris'
    }
  });

for (i = 0; i < E; i++)
  g.edges.push({
    id: 'e' + i,
    source: 'n' + (Math.random() * N | 0),
    target: 'n' + (Math.random() * N | 0),
    size: Math.random(),
    color: '#ccc'
  });

var arrayUnique = function(a) {
    return a.reduce(function(p, c) {
        if (p.indexOf(c) < 0) p.push(c);
        return p;
    }, []);
};


var s = new sigma({
  graph: g,
  renderer: {
    container: document.getElementById('mtl_vis'),
    type: 'webgl'
  },
  settings: {
    nodeHaloColor: 'red',
    edgeHaloColor: 'red',
    nodeHaloSize: 10,
    edgeHaloSize: 2,
    scalingMode: 'inside',
    drawLabels: true
  },
});


s.bind('clickNode', function(e) {
	var nodeId = e.data.node.id;
	console.log(e);
});


var tooltipsConfig = {
  node: {
    show: 'overNode',
    hide: 'outNode',
    cssClass: 'sigma-tooltip',
    position: 'top',
    autoadjust: true,
    template:
    '<div class="arrow"></div>' +
    ' <div class="sigma-tooltip-header">{{label}}</div>' +
    '  <div class="sigma-tooltip-body">' +
    '    <table>' +
    '      <tr><th>Name</th> <td>{{data.name}}</td></tr>' +
    '      <tr><th>Gender</th> <td>{{data.gender}}</td></tr>' +
    '      <tr><th>Age</th> <td>{{data.age}}</td></tr>' +
    '      <tr><th>City</th> <td>{{data.city}}</td></tr>' +
    '    </table>' +
    '  </div>' +
    '  <div class="sigma-tooltip-footer">Number of connections: {{degree}}</div>',
    renderer: function(node, template) {
      // The function context is s.graph
      node.degree = this.degree(node.id);

      // Returns an HTML string:
      //return Mustache.render(template, node);

      // Returns a DOM Element:
      var el = document.createElement('div');
      return el.innerHTML = Mustache.render(template, node);
    }
  }
};

var tooltipsWebgl = sigma.plugins.tooltips(s, s.renderers[0], tooltipsConfig);


function getAdjacents(e) {

  var adjacentNodes = [],
      adjacentEdges = [];

  e.data.nodes.forEach(function(node) {
    s.graph.adjacentNodes(node.id).forEach(function(n) {
      adjacentNodes.push(n);
    })
  });

  // Get adjacent edges:
  e.data.nodes.forEach(function(node) {
    s.graph.adjacentEdges(node.id).forEach(function(edge) {
      adjacentEdges.push(edge);
    })
  });

  // Remove duplicates:
  adjacentEdges = arrayUnique(adjacentEdges);

  var theAdjacents = {
    nodes: adjacentNodes,
    edges: adjacentEdges
  };

  return theAdjacents;
}

function doHalo(e) {
  var adjacents = getAdjacents(e);
  // Render halo:
  s.renderers[0].halo(adjacents);
}

s.bind('overNodes', function(e) {
  document.body.style.cursor = "pointer";
  doHalo(e);
}).bind('outNodes',function(){
  // remove halo
  document.body.style.cursor = "default";
  s.renderers[0].halo();
});


s.refresh();


});
```

```css
#mtl_vis {
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  position: absolute; }

    .sigma-tooltip {
      max-width: 240px;
      max-height: 280px;
      background-color: rgb(249, 247, 237);
      box-shadow: 0 2px 6px rgba(0,0,0,0.3);
      border-radius: 6px;
    }

    .sigma-tooltip-header {
      font-variant: small-caps;
      font-size: 120%;
      color: #437356;
      border-bottom: 1px solid #aac789;
      padding: 10px;
    }

    .sigma-tooltip-body {
      padding: 10px;
    }

    .sigma-tooltip-body th {
      color: #999;
      text-align: left;
    }

    .sigma-tooltip-footer {
      padding: 10px;
      border-top: 1px solid #aac789;
    }

    .sigma-tooltip > .arrow {
      border-width: 10px;
      position: absolute;
      display: block;
      width: 0;
      height: 0;
      border-color: transparent;
      border-style: solid;
    }

    .sigma-tooltip.top {
      margin-top: -12px;
    }
    .sigma-tooltip.top > .arrow {
      left: 50%;
      bottom: -10px;
      margin-left: -10px;
      border-top-color: rgb(249, 247, 237);
      border-bottom-width: 0;
    }

    .sigma-tooltip.bottom {
      margin-top: 12px;
    }
    .sigma-tooltip.bottom > .arrow {
      left: 50%;
      top: -10px;
      margin-left: -10px;
      border-bottom-color: rgb(249, 247, 237);
      border-top-width: 0;
    }

    .sigma-tooltip.left {
      margin-left: -12px;
    }
    .sigma-tooltip.left > .arrow {
      top: 50%;
      right: -10px;
      margin-top: -10px;
      border-left-color: rgb(249, 247, 237);
      border-right-width: 0;
    }

    .sigma-tooltip.right {
      margin-left: 12px;
    }
    .sigma-tooltip.right > .arrow {
      top: 50%;
      left: -10px;
      margin-top: -10px;
      border-right-color: rgb(249, 247, 237);
      border-left-width: 0;
    }
```
